// <auto-generated />
using FurkanAslan_Restoran.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurkanAslanRestoran.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230630171333_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurkanAslan_Restoran.Models.Icecek", b =>
                {
                    b.Property<int>("Icecek_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Icecek_Id"));

                    b.Property<string>("Icecek_Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Icecek_Adet")
                        .HasColumnType("int");

                    b.Property<int>("Icecek_Kat_Id")
                        .HasColumnType("int");

                    b.Property<int>("Icecek_Miktar")
                        .HasColumnType("int");

                    b.Property<string>("Icecek_Skt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Icecek_Id");

                    b.ToTable("Iceceks");
                });

            modelBuilder.Entity("FurkanAslan_Restoran.Models.Malzeme", b =>
                {
                    b.Property<int>("Mal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mal_Id"));

                    b.Property<string>("Mal_Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mal_Adet")
                        .HasColumnType("int");

                    b.Property<string>("Mal_Skt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mal_Sube")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mal_Uretimy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mal_Id");

                    b.ToTable("Malzemes");
                });

            modelBuilder.Entity("FurkanAslan_Restoran.Models.Yemek", b =>
                {
                    b.Property<int>("Ymk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ymk_Id"));

                    b.Property<string>("Ymk_Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ymk_Durum")
                        .HasColumnType("int");

                    b.Property<int>("Ymk_Kat_Id")
                        .HasColumnType("int");

                    b.Property<int>("Ymk_Sef_Id")
                        .HasColumnType("int");

                    b.Property<int>("Ymk_Spr_Id")
                        .HasColumnType("int");

                    b.HasKey("Ymk_Id");

                    b.ToTable("Yemeks");
                });
#pragma warning restore 612, 618
        }
    }
}
